nacos:
  config:
    server-addr: 47.121.116.149:8848
    username: nacos
    password: kwangnacos123
    data-ids: study,index
    type: yaml
    group: prod
    auto-refreshed: true
    bootstrap:
      enable: true
      log-enable: false
