nacos:
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: kwangnacos123
    data-id: study-prod
    type: yaml
    group: DEFAULT_GROUP
    auto-refreshed: true
    bootstrap:
      enable: true